info:
  port: 3333
  listen: false
  name: "ArcAPI"

filesystem:
  userspace_size: 2147483648  # 2 GiB

security:
  auth_code: null
  admin_code: null  # `null` means admin is disabled
  token_lifetime: 604800  # 1 week in seconds

storage:
  root: "data"
  database: "arcos.sqlite"
  filesystem: null  # `null` means disabled
  template: "template"  # to disable templates set this to `null`
